name: Android Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: example/

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - run: flutter pub get
      - run: flutter build apk

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: android/



