# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:dev

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: format
        run: dartfmt -n --set-exit-if-changed .
      - name: analyzer
        run: dartanalyzer --fatal-warnings --fatal-infos .
      - name: Run tests
        run: pub run test
